# Starship Prompt - Catppuccin Mocha Theme

format = """
[](#cba6f7)\
$os\
$username\
[](bg:#89b4fa fg:#cba6f7)\
$directory\
[](fg:#89b4fa bg:#74c7ec)\
$git_branch\
$git_status\
[](fg:#74c7ec bg:#94e2d5)\
$nodejs\
$rust\
$golang\
$python\
$ruby\
[](fg:#94e2d5 bg:#313244)\
$time\
[ ](fg:#313244)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:#cba6f7 fg:#1e1e2e"

[os.symbols]
Macos = "󰀵 "

[username]
show_always = true
style_user = "bg:#cba6f7 fg:#1e1e2e"
style_root = "bg:#cba6f7 fg:#1e1e2e"
format = '[ $user ]($style)'

[directory]
style = "fg:#1e1e2e bg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#74c7ec fg:#1e1e2e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#74c7ec fg:#1e1e2e"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#313244 fg:#cdd6f4"
format = '[ ♥ $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'
